FROM alpine:3.6
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

ENV build_deps="autoconf automake build-base"
ENV lib_deps="libtool db-dev boost-dev openssl-dev libevent-dev"
RUN apk add --update curl $build_deps $lib_deps && \
  curl -sSL https://github.com/dogecoin/dogecoin/archive/v1.10.0.tar.gz | tar -xzf - && \
  cd dogecoin-1.10.0 && ./autogen.sh && \
  ./configure --prefix=/usr --with-incompatible-bdb && \
  make && make install && \
  apk del $build_deps && rm -fr /var/cache/apk

ENTRYPOINT ["dogecoind"]
