FROM alpine:3.7
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

ENV build_deps="git autoconf automake build-base cmake linux-headers"
ENV lib_deps="python-dev libtool libgcc libgc++ bzip2-dev zlib-dev icu-dev db-dev openssl-dev libevent-dev miniupnpc-dev icu-dev"
RUN apk add --update curl $build_deps $lib_deps && \
  curl -sSL https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz | tar -xzf - && \
  mv boost_1_66_0 boost.src && \
  cd boost.src && ./bootstrap.sh && ./b2 --prefix=/usr --build-dir=boost.build --without-mpi link=static install && cd .. && \
  git clone https://github.com/clemahieu/raiblocks.git && \
  cd raiblocks && \
  git submodule init && git submodule update --recursive --remote && \
  git checkout 8c1114ec8b120cfa99de50a7358414ddda0eb99f && \
  git submodule update && \
  cmake -Wno-dev \
    ENABLE_AVX2=OFF RAIBLOCKS_GUI=OFF \
    PERMUTE_WITH_GATHER=OFF \
    PERMUTE_WITH_SHUFFLES=OFF . && \
  make && make install && mv ./rai_node /usr/bin/ && \
  mv librai_lib.so /usr/lib/ && \
  apk del $build_deps && rm -fr /var/cache/apk && \
  cd .. && rm -fr /raiblocks && rm -fr /boost.src

ENTRYPOINT ["rai_node"]
CMD [ "--daemon" ]
