FROM ubuntu:14.04
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

RUN apt-get update -y && \
  apt-get install -y curl software-properties-common \
    build-essential libtool \
    autotools-dev automake pkg-config libssl-dev \
    libevent-dev bsdmainutils libboost-system-dev \
    libboost-filesystem-dev libboost-chrono-dev \
    libboost-program-options-dev libboost-test-dev \
    libboost-thread-dev libminiupnpc-dev libzmq3-dev && \
  add-apt-repository ppa:bitcoin/bitcoin -y && \
  apt-get update -y && \
  apt-get install -y libdb4.8-dev libdb4.8++-dev && \
  curl -sSL https://github.com/Muvon/bitflip-token/archive/1.0.0.tar.gz | tar -xzf - && \
  cd bitflip-token-1.0.0 && \
  ./autogen.sh && \
  ./configure --prefix=/usr --with-incompatible-db && \
  make && make install && \
  apt-get remove build-essential autotools-dev automake \
    software-properties-common -y pkg-config && \
  apt-get clean && rm -fr /bitflip-token-1.0.0

ENTRYPOINT ["bitflipd"]
