FROM alpine:3.8
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

ENV build_deps="autoconf coreutils file git automake build-base wget"
ENV lib_deps="snappy snappy-dev zlib zlib-dev bzip2 bzip2-dev lz4 lz4-dev linux-headers openssl-dev"
RUN apk add --update curl $build_deps $lib_deps && \
  git clone https://github.com/yinqiwen/ardb.git && \
  cd ardb && git checkout 866f37b4716402c60a841b65d6fd7b3997b95a5e && \
  storage_engine=leveldb make && \
  mv src/ardb-* /usr/bin/ && \
  rm -fr /ardb && \
  apk del $build_deps && rm -fr /var/cache/apk
COPY redis-cli /usr/bin
ENTRYPOINT ["ardb-server"]
