FROM alpine:3.7
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

ENV build_deps="autoconf automake build-base"
ENV lib_deps="libtool db-dev boost-dev openssl-dev libevent-dev"
RUN apk add --update curl $build_deps $lib_deps && \
  curl -sSL https://github.com/Bitcoin-ABC/bitcoin-abc/archive/v0.16.2.tar.gz | tar -xzf - && \
  cd bitcoin-abc-0.16.2 && ./autogen.sh && \
  ./configure --prefix=/usr --with-incompatible-bdb --disable-wallet && \
  make HOST=x86_64-linux-gnu && make install && \
  apk del $build_deps && rm -fr /var/cache/apk && \
  rm -fr /bitcoin-abc-0.16.2

ENTRYPOINT ["bitcoind"]
