FROM ubuntu:16.04
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

ENV build_deps="scons protobuf-compiler build-essential git autoconf automake gcc cmake binutils"
ENV lib_deps="pkg-config libssl-dev libprotobuf-dev python-dev libtool libicu-dev libdb-dev libevent-dev libminiupnpc-dev"

RUN apt-get update -y && \ 
  apt-get install -y curl $build_deps $lib_deps && \
  curl -sSL https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz | tar -xzf - && \
  mv boost_1_66_0 boost.src && \
  cd boost.src && ./bootstrap.sh && ./b2 --prefix=/usr --build-dir=boost.build --without-mpi link=static install && cd .. && \
  curl -sSL https://github.com/CryptoManiac/rmcd/archive/0.90-rmc1.tar.gz | tar -xzf - && \
  cd rmcd-0.90-rmc1 && \
  scons && \
  mkdir -p /opt/ripple/bin/ && \
  mv build/rippled /opt/ripple/bin/ && \
  mv conf/rippled.cfg.example /opt/ripple/rippled.cfg && \
  mv conf/validators.txt.example /opt/ripple/validators.txt && \
  apt remove -y $build_deps && apt clean all && \
  rm -fr /var/cache/apt && \
  cd .. && rm -fr /rmcd-0.90-rmc1 && rm -fr /boost.src
  
EXPOSE 41234
ENTRYPOINT ["/opt/ripple/bin/rippled"]
CMD ["--net", "--silent", "--conf", "/etc/opt/ripple/rippled.cfg"]
