FROM alpine:3.6
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

ENV build_deps="autoconf automake build-base"
ENV lib_deps="libtool db-dev boost-dev openssl-dev libevent-dev"
RUN apk add --update curl $build_deps $lib_deps && \
  curl -sSL https://github.com/dashpay/dash/archive/v0.12.1.5.tar.gz | tar -xzf - && \
  cd dash-0.12.1.5 && ./autogen.sh && \
  ./configure --prefix=/usr --with-incompatible-bdb && \
  make && make install && \
  apk del $build_deps && rm -fr /var/cache/apk

ENTRYPOINT ["dashd"]
